version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # optional: ignore pins (example)
    # ignore:
    #   - dependency-name: "jax"
    #     versions:
    #       - "0.x"
