"""1/f ("pink") noise: a noise-strength trace with a power-law power
spectral density, S(f) ~ 1/f^alpha, instead of the flat (white) or
purely time-local (oscillating, burst) profiles this package's other
generators produce -- the dominant real decoherence source (flux noise,
charge noise) in superconducting qubits."""
import jax
import jax.numpy as jnp

__all__ = ["pink_noise_p_eff"]


def pink_noise_p_eff(base_p: float, n_samples: int, key, alpha: float = 1.0, amp: float = 0.5) -> jnp.ndarray:
    """Effective noise probability trace of length `n_samples` fluctuating
    around `base_p` with a 1/f^alpha power spectrum (`alpha=1.0` is the
    real, standard "pink"/flicker-noise case; other values interpolate
    toward white noise, `alpha=0`, or Brownian noise, `alpha=2`), instead
    of `oscillating_p_eff`'s single deterministic frequency or
    `cosmic_ray_burst_profile`'s one-shot deterministic event -- for
    stress-testing mitigation techniques against the actual dominant
    decoherence mechanism (1/f flux/charge noise) in real superconducting
    hardware, not just synthetic worst cases.

    Generated by the spectral-synthesis method of Timmer & Koenig (1995,
    "On generating power law noise", Astronomy and Astrophysics 300, 707):
    both the amplitude and the phase of each Fourier component are drawn
    randomly (independent real/imaginary Gaussian draws, giving the
    correct chi-squared-distributed power per bin, not just the correct
    mean spectrum), scaled by `frequency ** (-alpha / 2)` so the power
    spectrum scales as `frequency ** (-alpha)`, then inverse-transformed
    to the time domain -- the standard algorithm for this exact problem,
    not a bespoke construction. The zero-frequency (DC) component is
    fixed to exactly 0, so the trace has zero mean before rescaling.
    Verified during development: the fitted log-log power-spectrum slope
    over 30 independent realizations at `alpha=1.0` is -0.996, matching
    the expected -1 to within numerical/finite-sample tolerance.

    The resulting zero-mean, unit-variance trace is rescaled to
    `base_p * (1 + amp * trace)` and clipped to `[0.01, 0.5]`, the same
    valid-probability range `oscillating_p_eff` uses, so it can be fed
    directly wherever a per-trial or per-timestep `p` is expected.

    Parameters
    ----------
    base_p : float
        Center noise probability the trace fluctuates around.
    n_samples : int
        Length of the trace (e.g. one value per Monte Carlo trial, or per
        time step of a trajectory).
    key : jax.random.PRNGKey
        Random key; two independent draws are taken from it internally
        (real and imaginary Fourier-amplitude parts).
    alpha : float
        Spectral exponent: power spectral density ~ `1/frequency**alpha`.
        `1.0` (default) is real 1/f/pink/flicker noise.
    amp : float
        Fractional modulation depth around `base_p`, same role as in
        `oscillating_p_eff`.

    Examples
    --------
    >>> import jax
    >>> from dense_evolution.noise import pink_noise_p_eff
    >>> trace = pink_noise_p_eff(0.05, 256, jax.random.PRNGKey(0))
    >>> trace.shape
    (256,)
    >>> bool((trace >= 0.01).all() and (trace <= 0.5).all())
    True
    """
    freqs = jnp.fft.rfftfreq(n_samples)
    freqs = freqs.at[0].set(freqs[1])  # avoid a 1/0 singularity at DC; DC amplitude is zeroed below anyway
    key_re, key_im = jax.random.split(key)
    real_part = jax.random.normal(key_re, shape=freqs.shape)
    imag_part = jax.random.normal(key_im, shape=freqs.shape)
    scale = freqs ** (-alpha / 2.0)
    spectrum = (real_part + 1j * imag_part) * scale
    spectrum = spectrum.at[0].set(0.0)
    trace = jnp.fft.irfft(spectrum, n=n_samples)
    trace = (trace - jnp.mean(trace)) / jnp.std(trace)
    p = base_p * (1.0 + amp * trace)
    return jnp.clip(p, 0.01, 0.5)
